#include <cstdio>
#include <cstdlib>

#include "../ast/ast.h"
#include "semantic.h"

/* Generated by bison/flex */
int yyparse();
int yylex_destroy();
extern FILE* yyin;
extern astNode* ast_root;

int main(int argc, char** argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s <input_file>\n", argv[0]);
        return 1;
    }

    /* Open input file */
    yyin = fopen(argv[1], "r");
    if (!yyin) {
        perror("fopen");
        return 1;
    }

    /* Syntax analysis: lex + parse, build AST */
    int parse_result = yyparse();
    fclose(yyin);

    if (parse_result != 0 || ast_root == NULL) {
        fprintf(stderr, "Parse failed.\n");
        yylex_destroy();
        return 1;
    }

    printNode(ast_root, 0);

    /* Semantic analysis */
    int sem_result = semantic_check(ast_root);
    if (sem_result != 0) {
        fprintf(stderr, "Semantic analysis failed.\n");
        freeNode(ast_root);
        yylex_destroy();
        return 1;
    }

    /* Part 2: IR builder (not yet implemented) */
    /* LLVMModuleRef module = build_ir(ast_root); */
    /* if (!module) { ... cleanup ... } */

    /* Part 3: Optimizer (not yet implemented) */
    /* optimize(module); */

    /* Part 4: Assembly code generator (not yet implemented) */
    /* generate_asm(module, output_file); */

    /* Cleanup */
    freeNode(ast_root);
    yylex_destroy();
    /* LLVMDisposeModule(module); */
    /* LLVMShutdown();            */

    return 0;
}
